apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: web-server
  labels: 
   type: rs
spec: 
  selector:
    matchLabels: 
     type: app-replica

  replicas: 5
  
  template:
    metadata:
      name: replica-pod
      labels: 
        type: app-replica
    spec: 
      containers:
       - name: replica-cont
         image: nginx
